source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'grape'
gem 'grape-entity'
gem 'hashie-forbidden_attributes'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :test do
  gem 'rspec-rails'
end

